# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sigmarl.bridge import sigmarl_env_pb2 as sigmarl__env__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sigmarl_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SigmaRLEnvStub(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpaces = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/GetSpaces',
                request_serializer=sigmarl__env__pb2.Empty.SerializeToString,
                response_deserializer=sigmarl__env__pb2.SpacesInfo.FromString,
                _registered_method=True)
        self.GetWeightCount = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/GetWeightCount',
                request_serializer=sigmarl__env__pb2.Empty.SerializeToString,
                response_deserializer=sigmarl__env__pb2.WeightCountInfo.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/Configure',
                request_serializer=sigmarl__env__pb2.ScenarioConfig.SerializeToString,
                response_deserializer=sigmarl__env__pb2.Ack.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/Reset',
                request_serializer=sigmarl__env__pb2.ResetRequest.SerializeToString,
                response_deserializer=sigmarl__env__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/Step',
                request_serializer=sigmarl__env__pb2.StepRequest.SerializeToString,
                response_deserializer=sigmarl__env__pb2.StepResponse.FromString,
                _registered_method=True)
        self.EvaluateWeights = channel.unary_unary(
                '/sigmarl.SigmaRLEnv/EvaluateWeights',
                request_serializer=sigmarl__env__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=sigmarl__env__pb2.EvaluateResponse.FromString,
                _registered_method=True)


class SigmaRLEnvServicer(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def GetSpaces(self, request, context):
        """Introspect the configured environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeightCount(self, request, context):
        """Total number of scalar policy parameters (for EA weight vectors).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """(Re-)configure the scenario.  Must be called before Reset/Step if the
        default config (intersection_1, 4 agents, 1 env, cpu) is not suitable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the environment.  Returns the initial observations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance one timestep.  Java supplies actions, Python returns next state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateWeights(self, request, context):
        """EA mode: load a flat weight vector, run n_episodes, return fitness.
        Java owns the learning loop; Python just evaluates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SigmaRLEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpaces,
                    request_deserializer=sigmarl__env__pb2.Empty.FromString,
                    response_serializer=sigmarl__env__pb2.SpacesInfo.SerializeToString,
            ),
            'GetWeightCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeightCount,
                    request_deserializer=sigmarl__env__pb2.Empty.FromString,
                    response_serializer=sigmarl__env__pb2.WeightCountInfo.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=sigmarl__env__pb2.ScenarioConfig.FromString,
                    response_serializer=sigmarl__env__pb2.Ack.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=sigmarl__env__pb2.ResetRequest.FromString,
                    response_serializer=sigmarl__env__pb2.StepResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=sigmarl__env__pb2.StepRequest.FromString,
                    response_serializer=sigmarl__env__pb2.StepResponse.SerializeToString,
            ),
            'EvaluateWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateWeights,
                    request_deserializer=sigmarl__env__pb2.EvaluateRequest.FromString,
                    response_serializer=sigmarl__env__pb2.EvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sigmarl.SigmaRLEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sigmarl.SigmaRLEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SigmaRLEnv(object):
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetSpaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/GetSpaces',
            sigmarl__env__pb2.Empty.SerializeToString,
            sigmarl__env__pb2.SpacesInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeightCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/GetWeightCount',
            sigmarl__env__pb2.Empty.SerializeToString,
            sigmarl__env__pb2.WeightCountInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/Configure',
            sigmarl__env__pb2.ScenarioConfig.SerializeToString,
            sigmarl__env__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/Reset',
            sigmarl__env__pb2.ResetRequest.SerializeToString,
            sigmarl__env__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/Step',
            sigmarl__env__pb2.StepRequest.SerializeToString,
            sigmarl__env__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sigmarl.SigmaRLEnv/EvaluateWeights',
            sigmarl__env__pb2.EvaluateRequest.SerializeToString,
            sigmarl__env__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
