#!/usr/bin/env bash
# Regenerate gRPC stubs from sigmarl/bridge/sigmarl_env.proto.
#
# Python stubs are written back into sigmarl/bridge/.
# Java stubs are generated by Maven during `mvn package` — see java-client/pom.xml.
#
# Run from the repo root:
#   bash scripts/generate_proto.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROTO_SRC="${REPO_ROOT}/sigmarl/bridge"
PROTO_FILE="${PROTO_SRC}/sigmarl_env.proto"

echo "Generating Python stubs from ${PROTO_FILE} ..."

python -m grpc_tools.protoc \
  --proto_path="${PROTO_SRC}" \
  --python_out="${PROTO_SRC}" \
  --grpc_python_out="${PROTO_SRC}" \
  "${PROTO_FILE}"

# grpc_tools writes imports as absolute; fix to relative for package use
sed -i '' 's/^import sigmarl_env_pb2/from sigmarl.bridge import sigmarl_env_pb2/' \
  "${PROTO_SRC}/sigmarl_env_pb2_grpc.py" 2>/dev/null || \
sed -i    's/^import sigmarl_env_pb2/from sigmarl.bridge import sigmarl_env_pb2/' \
  "${PROTO_SRC}/sigmarl_env_pb2_grpc.py"

echo "Done. Python stubs written to ${PROTO_SRC}/"
echo ""
echo "For Java stubs, run:  cd java-client && mvn package"
